name: Hello World

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Hello, World!"
